### ISSUE TITLE
Getting Error on NodeJs 

### ISSUE THREAD

**Issue by yashkathe** [dajk/hltv-api#78] opened 2022-03-13 05:09 UTC
/home/yashkathe/NODEJS-projects/CLONES/csgo-news/node_modules/hltv-api/dist/teams.js:72
            throw new Error(error);
                  ^

Error: Error: There are no teams available, something went wrong. Please contact the library maintainer on https://github.com/dajk/hltv-api
    at Object.<anonymous> (/home/yashkathe/NODEJS-projects/CLONES/csgo-news/node_modules/hltv-api/dist/teams.js:72:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/yashkathe/NODEJS-projects/CLONES/csgo-news/node_modules/hltv-api/dist/teams.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Ta1al** [comment] 2022-03-13 07:18
I think it has been 2 weeks since the API stopped working

**Comment by yashkathe** [comment] 2022-03-13 08:13
And here I was, trying to refactor my code thinking I was doing something wrong. Well thanks for informing and do update this thread if the api is back up again. Thank you

**Comment by gustavo-dev** [comment] 2022-05-15 16:21
I did some testing and concluded the problem is that HLTV is blocking all requests because of bot protection. Changing the User-Agent in the source code from `node-fetch` to a real User-Agent solved the issue.

Using the [user-agents](https://www.npmjs.com/package/user-agents) library to generate a User-Agent might, instead of using `node-fetch`, be a good solution to this.

**Comment by dajk** [comment] 2022-08-08 23:40
Thanks for pointing this out, the fix has been released...closing..

**Closed by dajk** 2022-08-08 23:40 UTC
